import visualization_lib
import matplotlib.pyplot as plt

num=0
visualization_lib.plot_3d_filtered_h_traj(num)
visualization_lib.plot_3d_filtered_r_traj(num)
visualization_lib.plot_offline_3d_obs(num)
visualization_lib.plot_gen_3d_offline_r_traj(num)